"""State repository exports.

Persistence logic lives in focused modules under db/ and repositories/.
"""
from __future__ import annotations

from .db.connection import db_connect, db_transaction
from .db.schema import ensure_columns, init_db
from .helpers import (
    PROVIDER_ID_RE,
    first_result_url,
    is_relative_to_path,
    now_iso,
    safe_json,
    safe_unlink_under,
    validate_provider_id,
)
from .repositories.admin_auth import (
    LoginAttemptResult,
    change_admin_password,
    cleanup_admin_security_state,
    clear_admin_login_failures,
    create_admin_session,
    delete_admin_session,
    ensure_default_admin_user,
    get_admin_login_lock,
    get_admin_session,
    login_attempt_key,
    purge_expired_admin_sessions,
    purge_old_admin_login_attempts,
    record_admin_login_failure,
    verify_admin_login,
)
from .repositories.assets import (
    delete_asset,
    get_asset,
    list_assets,
    save_asset,
)
from .repositories.assistant_plans import save_assistant_plan
from .repositories.gateway_keys import (
    create_gateway_api_key,
    get_gateway_api_key,
    has_gateway_api_key_records,
    list_gateway_api_keys,
    revoke_gateway_api_key,
    update_gateway_api_key,
    update_gateway_api_key_last_used,
    verify_gateway_api_key,
)
from .repositories.generations import (
    clear_generations,
    clear_generations_and_collect_files,
    delete_generation_records_for_file,
    generation_metadata_by_filename,
    known_generated_local_paths,
    list_generation_files,
    record_generation,
)
from .repositories.jobs import (
    _JOB_COLUMNS,
    create_job,
    fail_job,
    find_recent_job_by_request_hash,
    get_job,
    get_job_by_external_task_id,
    list_jobs,
    update_job_status,
)
from .repositories.settings import (
    BUILTIN_PROVIDER_CONFIG_KEYS,
    apply_saved_config_to_runtime,
    builtin_provider_enabled,
    config_snapshot,
    delete_custom_provider,
    get_config,
    get_custom_provider,
    list_custom_providers,
    load_saved_settings,
    mask_secret,
    set_builtin_provider_enabled,
    set_config,
    set_config_many,
    update_custom_provider_enabled,
    update_custom_provider_sort,
    update_custom_provider_test,
    upsert_custom_provider,
)
from .repositories.table_rows import TABLE_SELECT_SQL, list_rows
from .repositories.uploads import DeleteUploadResult, delete_upload, save_upload
from .repositories.video_tasks import upsert_video_task

__all__ = [
    "BUILTIN_PROVIDER_CONFIG_KEYS",
    "DeleteUploadResult",
    "LoginAttemptResult",
    "PROVIDER_ID_RE",
    "TABLE_SELECT_SQL",
    "_JOB_COLUMNS",
    "apply_saved_config_to_runtime",
    "builtin_provider_enabled",
    "change_admin_password",
    "cleanup_admin_security_state",
    "clear_admin_login_failures",
    "clear_generations",
    "clear_generations_and_collect_files",
    "config_snapshot",
    "create_admin_session",
    "create_gateway_api_key",
    "create_job",
    "db_connect",
    "db_transaction",
    "delete_admin_session",
    "delete_asset",
    "delete_custom_provider",
    "delete_generation_records_for_file",
    "delete_upload",
    "ensure_columns",
    "ensure_default_admin_user",
    "fail_job",
    "find_recent_job_by_request_hash",
    "first_result_url",
    "generation_metadata_by_filename",
    "get_admin_login_lock",
    "get_admin_session",
    "get_asset",
    "get_config",
    "get_custom_provider",
    "get_gateway_api_key",
    "get_job",
    "get_job_by_external_task_id",
    "has_gateway_api_key_records",
    "init_db",
    "is_relative_to_path",
    "known_generated_local_paths",
    "list_assets",
    "list_custom_providers",
    "list_gateway_api_keys",
    "list_generation_files",
    "list_jobs",
    "list_rows",
    "load_saved_settings",
    "login_attempt_key",
    "mask_secret",
    "now_iso",
    "purge_expired_admin_sessions",
    "purge_old_admin_login_attempts",
    "record_admin_login_failure",
    "record_generation",
    "revoke_gateway_api_key",
    "safe_json",
    "safe_unlink_under",
    "save_asset",
    "save_assistant_plan",
    "save_upload",
    "set_builtin_provider_enabled",
    "set_config",
    "set_config_many",
    "update_custom_provider_enabled",
    "update_custom_provider_sort",
    "update_custom_provider_test",
    "update_gateway_api_key",
    "update_gateway_api_key_last_used",
    "update_job_status",
    "upsert_custom_provider",
    "upsert_video_task",
    "validate_provider_id",
    "verify_admin_login",
    "verify_gateway_api_key",
]
